export const ProjectObj = {
  project1: {
    title: "Fridge Haiku",
    summary:
      "Fridge Haiku is a website that you can generate fridge-magnet-like words with a topic to create poetry. You can log in with firebase authentication to save or play with out sign in. Words are generated by fetching JSON format data from datamuse API.",
    madeWithMain: ["React.js", "Redux", "Firebase"],
    madeWithSub: [
      "Materialize",
      "Datamuse API",
      "HTML5",
      "CSS3",
      "html2canvas",
    ],
    description:
      "Your fridge magnet poetry is gone at shared house refrigerator? This is a web app for you! Fridge Haiku is a website that you can generate fridge-magnet-like words with a topic to create poetry. You can log in with firebase authentication to save or play with out sign in. Also you can share to your twitter as an image (Comming soon...!). Words are generated by fetching JSON format data from datamuse API.",
  },
  project2: {
    title: "Image Search",
    summary:
      "Simple image search, when user type search term to the input the website fetches image from unsplash API. My first React.js app.",
    madeWithMain: ["React.js", "axios", "Semantic-ui"],
    madeWithSub: ["Unsplash API", "HTML5", "CSS3"],
    description:
      "My first React.js-app. Simple image search, when user type search term to the input the website fetches image from unsplash API.",
  },
  project3: {
    title: "Noella Trading Company Ltd.",
    summary:
      "Company website for the gift stores based in Vancouver. In progress, will be updated upon company requests.",
    madeWithMain: ["React.js", "HTML5", "CSS3", "Sass"],
    // madeWithSub: [
    //   "Materialize",

    // ],
    description:
      "My first individual responsive website project after I learned HTML/CSS for 2 months. Since the company didn't have website yet, I built this website from scratch with Figma, HTML5, CSS3, JavaScript and jQuery. After I learned React for 2 months and get to know some principals of UI/UX design with online tutorials, I rebuilt website with React.js. Still discussing what functions they need, will be updated with additional functionality like online shop and Instagram API. Noella means Christmas in French, and the company owns two gift stores with different concepts in Vancouver, so I tried design website that fits to both of them.",
  },
};
